--
-- PostgreSQL database dump
--

\restrict pKKZaASOAVNp7cEHCKQWSLCti4hgjRc94EudQsvxtvROoLCYlNh4rdJZxOWQEkH

-- Dumped from database version 17.11
-- Dumped by pg_dump version 17.11

-- Started on 2026-10-08 10:45:03

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 224 (class 1259 OID 17193)
-- Name: assinatura; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.assinatura (
    id_ass bigint NOT NULL,
    forma_pagto character varying(50) NOT NULL,
    valor numeric(10,2) NOT NULL,
    id_usr bigint NOT NULL,
    CONSTRAINT chk_assinatura_valor CHECK ((valor >= 0.00))
);


ALTER TABLE public.assinatura OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 17192)
-- Name: assinatura_id_ass_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.assinatura ALTER COLUMN id_ass ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assinatura_id_ass_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 17207)
-- Name: chat; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.chat (
    id_chat bigint NOT NULL,
    dt_inicio timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    id_usr_01 bigint NOT NULL,
    id_usr_02 bigint NOT NULL,
    CONSTRAINT chk_chat_usuarios_diferentes CHECK ((id_usr_01 <> id_usr_02))
);


ALTER TABLE public.chat OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 17206)
-- Name: chat_id_chat_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.chat ALTER COLUMN id_chat ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_id_chat_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 17260)
-- Name: conexao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.conexao (
    id_conexao bigint NOT NULL,
    status_conexao character varying(50) DEFAULT 'PENDENTE'::character varying NOT NULL,
    dt_solicitacao timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    id_user_solicit bigint NOT NULL,
    id_user_receb bigint NOT NULL,
    CONSTRAINT chk_conexao_status CHECK (((status_conexao)::text = ANY ((ARRAY['PENDENTE'::character varying, 'ACEITO'::character varying, 'RECUSADO'::character varying])::text[]))),
    CONSTRAINT chk_conexao_usuarios_diferentes CHECK ((id_user_solicit <> id_user_receb))
);


ALTER TABLE public.conexao OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 17259)
-- Name: conexao_id_conexao_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.conexao ALTER COLUMN id_conexao ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conexao_id_conexao_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 17246)
-- Name: conteudo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.conteudo (
    id_cont bigint NOT NULL,
    titulo_cont character varying(255) NOT NULL,
    desc_cont text,
    mat_text_content text NOT NULL,
    duracao_cont integer,
    data_pub date NOT NULL,
    id_mod bigint NOT NULL,
    CONSTRAINT chk_conteudo_duracao CHECK ((duracao_cont >= 1))
);


ALTER TABLE public.conteudo OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 17245)
-- Name: conteudo_id_cont_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.conteudo ALTER COLUMN id_cont ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conteudo_id_cont_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 17326)
-- Name: conteudo_interesses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.conteudo_interesses (
    id_cont bigint NOT NULL,
    id_intr bigint NOT NULL
);


ALTER TABLE public.conteudo_interesses OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 17300)
-- Name: conteudo_pro; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.conteudo_pro (
    id_cont_pro bigint NOT NULL,
    titulo_cont_pro character varying(255) NOT NULL,
    desc_cont_pro text,
    mat_text_cont_pro text,
    anexos_cont_pro integer,
    duracao_cont_pro bigint DEFAULT 0,
    data_pub_cont_pro timestamp without time zone NOT NULL,
    CONSTRAINT chk_conteudo_pro_duracao CHECK ((duracao_cont_pro >= 0))
);


ALTER TABLE public.conteudo_pro OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 17299)
-- Name: conteudo_pro_id_cont_pro_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.conteudo_pro ALTER COLUMN id_cont_pro ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conteudo_pro_id_cont_pro_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 17404)
-- Name: denuncia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.denuncia (
    id_den bigint NOT NULL,
    motivo_den character varying(255) NOT NULL,
    status character varying(50) DEFAULT 'PENDENTE'::character varying NOT NULL,
    dt_denuncia timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    id_mod bigint NOT NULL,
    id_usr_denunciante bigint NOT NULL,
    CONSTRAINT chk_denuncia_status CHECK (((status)::text = ANY ((ARRAY['PENDENTE'::character varying, 'EM_ANALISE'::character varying, 'RESOLVIDA'::character varying, 'REJEITADA'::character varying])::text[])))
);


ALTER TABLE public.denuncia OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 17403)
-- Name: denuncia_id_den_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.denuncia ALTER COLUMN id_den ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.denuncia_id_den_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 17452)
-- Name: denuncia_mensagem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.denuncia_mensagem (
    id_msg bigint NOT NULL,
    id_den bigint NOT NULL
);


ALTER TABLE public.denuncia_mensagem OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 17467)
-- Name: denuncia_postagem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.denuncia_postagem (
    id_post bigint NOT NULL,
    id_den bigint NOT NULL
);


ALTER TABLE public.denuncia_postagem OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 17437)
-- Name: denuncia_usuaria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.denuncia_usuaria (
    id_usr_denunciada bigint NOT NULL,
    id_den bigint NOT NULL
);


ALTER TABLE public.denuncia_usuaria OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 17225)
-- Name: forum; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.forum (
    id_for bigint NOT NULL,
    titulo_for character varying(255) NOT NULL,
    desc_for character varying(255) DEFAULT NULL::character varying,
    capa_for character varying(255) DEFAULT NULL::character varying,
    dt_criacao timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    id_mod bigint NOT NULL,
    id_usr_criadora bigint NOT NULL
);


ALTER TABLE public.forum OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 17224)
-- Name: forum_id_for_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.forum ALTER COLUMN id_for ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forum_id_for_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 17185)
-- Name: interesses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.interesses (
    id_intr bigint NOT NULL,
    nome_intr character varying(100) NOT NULL
);


ALTER TABLE public.interesses OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 17184)
-- Name: interesses_id_intr_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.interesses ALTER COLUMN id_intr ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.interesses_id_intr_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 17372)
-- Name: mensagem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mensagem (
    id_msg bigint NOT NULL,
    cont_msg text NOT NULL,
    dt_envio timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    id_chat bigint NOT NULL,
    id_usr_emissor bigint NOT NULL
);


ALTER TABLE public.mensagem OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 17371)
-- Name: mensagem_id_msg_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mensagem ALTER COLUMN id_msg ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mensagem_id_msg_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 17175)
-- Name: moderadora; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.moderadora (
    id_mod bigint NOT NULL,
    nome_mod character varying(255) NOT NULL,
    email_mod character varying(255) NOT NULL,
    senha_mod character varying(255) NOT NULL
);


ALTER TABLE public.moderadora OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 17174)
-- Name: moderadora_id_mod_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.moderadora ALTER COLUMN id_mod ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.moderadora_id_mod_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 17280)
-- Name: postagem; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.postagem (
    id_post bigint NOT NULL,
    dt_post timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    cont_post text NOT NULL,
    img_post character varying(500) DEFAULT NULL::character varying,
    id_usr bigint NOT NULL,
    id_for bigint NOT NULL
);


ALTER TABLE public.postagem OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 17279)
-- Name: postagem_id_post_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.postagem ALTER COLUMN id_post ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.postagem_id_post_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 17391)
-- Name: relatorio_moderacao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.relatorio_moderacao (
    id_relat bigint NOT NULL,
    id_mod bigint NOT NULL,
    acao character varying(100) NOT NULL,
    dt_acao timestamp without time zone NOT NULL,
    "desc" text NOT NULL
);


ALTER TABLE public.relatorio_moderacao OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 17390)
-- Name: relatorio_moderacao_id_relat_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.relatorio_moderacao ALTER COLUMN id_relat ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.relatorio_moderacao_id_relat_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 17161)
-- Name: usuaria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuaria (
    id_usr bigint NOT NULL,
    nome_usr character varying(255) NOT NULL,
    email_usr character varying(255) NOT NULL,
    senha_usr character varying(255) NOT NULL,
    foto_usr character varying(500) DEFAULT NULL::character varying,
    cpf_usr character varying(14) NOT NULL,
    status_verificacao boolean DEFAULT false NOT NULL
);


ALTER TABLE public.usuaria OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 17309)
-- Name: usuaria_conteudo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuaria_conteudo (
    id_usr bigint NOT NULL,
    id_cont bigint NOT NULL,
    dt_acesso timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    progresso_cont numeric(5,2),
    CONSTRAINT chk_usuaria_conteudo_progresso CHECK (((progresso_cont >= 0.00) AND (progresso_cont <= 100.00)))
);


ALTER TABLE public.usuaria_conteudo OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 17356)
-- Name: usuaria_conteudo_pro; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuaria_conteudo_pro (
    id_usr bigint NOT NULL,
    id_cont_pro bigint NOT NULL
);


ALTER TABLE public.usuaria_conteudo_pro OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 17422)
-- Name: usuaria_forum; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuaria_forum (
    id_for bigint NOT NULL,
    id_usr bigint NOT NULL
);


ALTER TABLE public.usuaria_forum OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 17160)
-- Name: usuaria_id_usr_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuaria ALTER COLUMN id_usr ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuaria_id_usr_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 17341)
-- Name: usuaria_interesses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuaria_interesses (
    id_usr bigint NOT NULL,
    id_intr bigint NOT NULL
);


ALTER TABLE public.usuaria_interesses OWNER TO postgres;

--
-- TOC entry 4872 (class 2606 OID 17200)
-- Name: assinatura assinatura_id_usr_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assinatura
    ADD CONSTRAINT assinatura_id_usr_key UNIQUE (id_usr);


--
-- TOC entry 4874 (class 2606 OID 17198)
-- Name: assinatura assinatura_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assinatura
    ADD CONSTRAINT assinatura_pkey PRIMARY KEY (id_ass);


--
-- TOC entry 4876 (class 2606 OID 17213)
-- Name: chat chat_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT chat_pkey PRIMARY KEY (id_chat);


--
-- TOC entry 4882 (class 2606 OID 17268)
-- Name: conexao conexao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conexao
    ADD CONSTRAINT conexao_pkey PRIMARY KEY (id_conexao);


--
-- TOC entry 4890 (class 2606 OID 17330)
-- Name: conteudo_interesses conteudo_interesses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conteudo_interesses
    ADD CONSTRAINT conteudo_interesses_pkey PRIMARY KEY (id_cont, id_intr);


--
-- TOC entry 4880 (class 2606 OID 17253)
-- Name: conteudo conteudo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conteudo
    ADD CONSTRAINT conteudo_pkey PRIMARY KEY (id_cont);


--
-- TOC entry 4886 (class 2606 OID 17308)
-- Name: conteudo_pro conteudo_pro_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conteudo_pro
    ADD CONSTRAINT conteudo_pro_pkey PRIMARY KEY (id_cont_pro);


--
-- TOC entry 4906 (class 2606 OID 17456)
-- Name: denuncia_mensagem denuncia_mensagem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.denuncia_mensagem
    ADD CONSTRAINT denuncia_mensagem_pkey PRIMARY KEY (id_den, id_msg);


--
-- TOC entry 4900 (class 2606 OID 17411)
-- Name: denuncia denuncia_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.denuncia
    ADD CONSTRAINT denuncia_pkey PRIMARY KEY (id_den);


--
-- TOC entry 4908 (class 2606 OID 17471)
-- Name: denuncia_postagem denuncia_postagem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.denuncia_postagem
    ADD CONSTRAINT denuncia_postagem_pkey PRIMARY KEY (id_den, id_post);


--
-- TOC entry 4904 (class 2606 OID 17441)
-- Name: denuncia_usuaria denuncia_usuaria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.denuncia_usuaria
    ADD CONSTRAINT denuncia_usuaria_pkey PRIMARY KEY (id_den, id_usr_denunciada);


--
-- TOC entry 4878 (class 2606 OID 17234)
-- Name: forum forum_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forum
    ADD CONSTRAINT forum_pkey PRIMARY KEY (id_for);


--
-- TOC entry 4868 (class 2606 OID 17191)
-- Name: interesses interesses_nome_intr_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interesses
    ADD CONSTRAINT interesses_nome_intr_key UNIQUE (nome_intr);


--
-- TOC entry 4870 (class 2606 OID 17189)
-- Name: interesses interesses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.interesses
    ADD CONSTRAINT interesses_pkey PRIMARY KEY (id_intr);


--
-- TOC entry 4896 (class 2606 OID 17379)
-- Name: mensagem mensagem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mensagem
    ADD CONSTRAINT mensagem_pkey PRIMARY KEY (id_msg);


--
-- TOC entry 4864 (class 2606 OID 17183)
-- Name: moderadora moderadora_email_mod_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.moderadora
    ADD CONSTRAINT moderadora_email_mod_key UNIQUE (email_mod);


--
-- TOC entry 4866 (class 2606 OID 17181)
-- Name: moderadora moderadora_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.moderadora
    ADD CONSTRAINT moderadora_pkey PRIMARY KEY (id_mod);


--
-- TOC entry 4884 (class 2606 OID 17288)
-- Name: postagem postagem_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.postagem
    ADD CONSTRAINT postagem_pkey PRIMARY KEY (id_post);


--
-- TOC entry 4898 (class 2606 OID 17397)
-- Name: relatorio_moderacao relatorio_moderacao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.relatorio_moderacao
    ADD CONSTRAINT relatorio_moderacao_pkey PRIMARY KEY (id_relat);


--
-- TOC entry 4888 (class 2606 OID 17315)
-- Name: usuaria_conteudo usuaria_conteudo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuaria_conteudo
    ADD CONSTRAINT usuaria_conteudo_pkey PRIMARY KEY (id_usr, id_cont);


--
-- TOC entry 4894 (class 2606 OID 17360)
-- Name: usuaria_conteudo_pro usuaria_conteudo_pro_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuaria_conteudo_pro
    ADD CONSTRAINT usuaria_conteudo_pro_pkey PRIMARY KEY (id_usr, id_cont_pro);


--
-- TOC entry 4858 (class 2606 OID 17173)
-- Name: usuaria usuaria_cpf_usr_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuaria
    ADD CONSTRAINT usuaria_cpf_usr_key UNIQUE (cpf_usr);


--
-- TOC entry 4860 (class 2606 OID 17171)
-- Name: usuaria usuaria_email_usr_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuaria
    ADD CONSTRAINT usuaria_email_usr_key UNIQUE (email_usr);


--
-- TOC entry 4902 (class 2606 OID 17426)
-- Name: usuaria_forum usuaria_forum_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuaria_forum
    ADD CONSTRAINT usuaria_forum_pkey PRIMARY KEY (id_for, id_usr);


--
-- TOC entry 4892 (class 2606 OID 17345)
-- Name: usuaria_interesses usuaria_interesses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuaria_interesses
    ADD CONSTRAINT usuaria_interesses_pkey PRIMARY KEY (id_usr, id_intr);


--
-- TOC entry 4862 (class 2606 OID 17169)
-- Name: usuaria usuaria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuaria
    ADD CONSTRAINT usuaria_pkey PRIMARY KEY (id_usr);


--
-- TOC entry 4909 (class 2606 OID 17201)
-- Name: assinatura fk_assinatura_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.assinatura
    ADD CONSTRAINT fk_assinatura_usuario FOREIGN KEY (id_usr) REFERENCES public.usuaria(id_usr);


--
-- TOC entry 4910 (class 2606 OID 17214)
-- Name: chat fk_chat_usr_01; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT fk_chat_usr_01 FOREIGN KEY (id_usr_01) REFERENCES public.usuaria(id_usr);


--
-- TOC entry 4911 (class 2606 OID 17219)
-- Name: chat fk_chat_usr_02; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.chat
    ADD CONSTRAINT fk_chat_usr_02 FOREIGN KEY (id_usr_02) REFERENCES public.usuaria(id_usr);


--
-- TOC entry 4915 (class 2606 OID 17274)
-- Name: conexao fk_conexao_recebedor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conexao
    ADD CONSTRAINT fk_conexao_recebedor FOREIGN KEY (id_user_receb) REFERENCES public.usuaria(id_usr);


--
-- TOC entry 4916 (class 2606 OID 17269)
-- Name: conexao fk_conexao_solicitante; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conexao
    ADD CONSTRAINT fk_conexao_solicitante FOREIGN KEY (id_user_solicit) REFERENCES public.usuaria(id_usr);


--
-- TOC entry 4921 (class 2606 OID 17331)
-- Name: conteudo_interesses fk_conteudo_interesses_conteudo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conteudo_interesses
    ADD CONSTRAINT fk_conteudo_interesses_conteudo FOREIGN KEY (id_cont) REFERENCES public.conteudo(id_cont) ON DELETE CASCADE;


--
-- TOC entry 4922 (class 2606 OID 17336)
-- Name: conteudo_interesses fk_conteudo_interesses_interesse; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conteudo_interesses
    ADD CONSTRAINT fk_conteudo_interesses_interesse FOREIGN KEY (id_intr) REFERENCES public.interesses(id_intr) ON DELETE CASCADE;


--
-- TOC entry 4914 (class 2606 OID 17254)
-- Name: conteudo fk_conteudo_moderadora; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.conteudo
    ADD CONSTRAINT fk_conteudo_moderadora FOREIGN KEY (id_mod) REFERENCES public.moderadora(id_mod);


--
-- TOC entry 4930 (class 2606 OID 17417)
-- Name: denuncia fk_denuncia_denunciante; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.denuncia
    ADD CONSTRAINT fk_denuncia_denunciante FOREIGN KEY (id_usr_denunciante) REFERENCES public.usuaria(id_usr);


--
-- TOC entry 4936 (class 2606 OID 17462)
-- Name: denuncia_mensagem fk_denuncia_mensagem_denuncia; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.denuncia_mensagem
    ADD CONSTRAINT fk_denuncia_mensagem_denuncia FOREIGN KEY (id_den) REFERENCES public.denuncia(id_den) ON DELETE CASCADE;


--
-- TOC entry 4937 (class 2606 OID 17457)
-- Name: denuncia_mensagem fk_denuncia_mensagem_mensagem; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.denuncia_mensagem
    ADD CONSTRAINT fk_denuncia_mensagem_mensagem FOREIGN KEY (id_msg) REFERENCES public.mensagem(id_msg);


--
-- TOC entry 4931 (class 2606 OID 17412)
-- Name: denuncia fk_denuncia_moderadora; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.denuncia
    ADD CONSTRAINT fk_denuncia_moderadora FOREIGN KEY (id_mod) REFERENCES public.moderadora(id_mod);


--
-- TOC entry 4938 (class 2606 OID 17477)
-- Name: denuncia_postagem fk_denuncia_postagem_denuncia; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.denuncia_postagem
    ADD CONSTRAINT fk_denuncia_postagem_denuncia FOREIGN KEY (id_den) REFERENCES public.denuncia(id_den) ON DELETE CASCADE;


--
-- TOC entry 4939 (class 2606 OID 17472)
-- Name: denuncia_postagem fk_denuncia_postagem_postagem; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.denuncia_postagem
    ADD CONSTRAINT fk_denuncia_postagem_postagem FOREIGN KEY (id_post) REFERENCES public.postagem(id_post);


--
-- TOC entry 4934 (class 2606 OID 17447)
-- Name: denuncia_usuaria fk_denuncia_usuaria_denuncia; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.denuncia_usuaria
    ADD CONSTRAINT fk_denuncia_usuaria_denuncia FOREIGN KEY (id_den) REFERENCES public.denuncia(id_den) ON DELETE CASCADE;


--
-- TOC entry 4935 (class 2606 OID 17442)
-- Name: denuncia_usuaria fk_denuncia_usuaria_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.denuncia_usuaria
    ADD CONSTRAINT fk_denuncia_usuaria_usuario FOREIGN KEY (id_usr_denunciada) REFERENCES public.usuaria(id_usr);


--
-- TOC entry 4912 (class 2606 OID 17240)
-- Name: forum fk_forum_criadora; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forum
    ADD CONSTRAINT fk_forum_criadora FOREIGN KEY (id_usr_criadora) REFERENCES public.usuaria(id_usr);


--
-- TOC entry 4913 (class 2606 OID 17235)
-- Name: forum fk_forum_moderadora; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.forum
    ADD CONSTRAINT fk_forum_moderadora FOREIGN KEY (id_mod) REFERENCES public.moderadora(id_mod);


--
-- TOC entry 4927 (class 2606 OID 17380)
-- Name: mensagem fk_mensagem_chat; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mensagem
    ADD CONSTRAINT fk_mensagem_chat FOREIGN KEY (id_chat) REFERENCES public.chat(id_chat);


--
-- TOC entry 4928 (class 2606 OID 17385)
-- Name: mensagem fk_mensagem_emissor; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mensagem
    ADD CONSTRAINT fk_mensagem_emissor FOREIGN KEY (id_usr_emissor) REFERENCES public.usuaria(id_usr);


--
-- TOC entry 4917 (class 2606 OID 17294)
-- Name: postagem fk_postagem_forum; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.postagem
    ADD CONSTRAINT fk_postagem_forum FOREIGN KEY (id_for) REFERENCES public.forum(id_for);


--
-- TOC entry 4918 (class 2606 OID 17289)
-- Name: postagem fk_postagem_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.postagem
    ADD CONSTRAINT fk_postagem_usuario FOREIGN KEY (id_usr) REFERENCES public.usuaria(id_usr);


--
-- TOC entry 4929 (class 2606 OID 17398)
-- Name: relatorio_moderacao fk_relatorio_moderadora; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.relatorio_moderacao
    ADD CONSTRAINT fk_relatorio_moderadora FOREIGN KEY (id_mod) REFERENCES public.moderadora(id_mod);


--
-- TOC entry 4919 (class 2606 OID 17321)
-- Name: usuaria_conteudo fk_usuaria_conteudo_conteudo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuaria_conteudo
    ADD CONSTRAINT fk_usuaria_conteudo_conteudo FOREIGN KEY (id_cont) REFERENCES public.conteudo(id_cont) ON DELETE CASCADE;


--
-- TOC entry 4925 (class 2606 OID 17366)
-- Name: usuaria_conteudo_pro fk_usuaria_conteudo_pro_conteudo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuaria_conteudo_pro
    ADD CONSTRAINT fk_usuaria_conteudo_pro_conteudo FOREIGN KEY (id_cont_pro) REFERENCES public.conteudo_pro(id_cont_pro) ON DELETE CASCADE;


--
-- TOC entry 4926 (class 2606 OID 17361)
-- Name: usuaria_conteudo_pro fk_usuaria_conteudo_pro_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuaria_conteudo_pro
    ADD CONSTRAINT fk_usuaria_conteudo_pro_usuario FOREIGN KEY (id_usr) REFERENCES public.usuaria(id_usr) ON DELETE CASCADE;


--
-- TOC entry 4920 (class 2606 OID 17316)
-- Name: usuaria_conteudo fk_usuaria_conteudo_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuaria_conteudo
    ADD CONSTRAINT fk_usuaria_conteudo_usuario FOREIGN KEY (id_usr) REFERENCES public.usuaria(id_usr) ON DELETE CASCADE;


--
-- TOC entry 4932 (class 2606 OID 17427)
-- Name: usuaria_forum fk_usuaria_forum_forum; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuaria_forum
    ADD CONSTRAINT fk_usuaria_forum_forum FOREIGN KEY (id_for) REFERENCES public.forum(id_for) ON DELETE CASCADE;


--
-- TOC entry 4933 (class 2606 OID 17432)
-- Name: usuaria_forum fk_usuaria_forum_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuaria_forum
    ADD CONSTRAINT fk_usuaria_forum_usuario FOREIGN KEY (id_usr) REFERENCES public.usuaria(id_usr) ON DELETE CASCADE;


--
-- TOC entry 4923 (class 2606 OID 17351)
-- Name: usuaria_interesses fk_usuaria_interesses_interesse; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuaria_interesses
    ADD CONSTRAINT fk_usuaria_interesses_interesse FOREIGN KEY (id_intr) REFERENCES public.interesses(id_intr) ON DELETE CASCADE;


--
-- TOC entry 4924 (class 2606 OID 17346)
-- Name: usuaria_interesses fk_usuaria_interesses_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuaria_interesses
    ADD CONSTRAINT fk_usuaria_interesses_usuario FOREIGN KEY (id_usr) REFERENCES public.usuaria(id_usr) ON DELETE CASCADE;


-- Completed on 2026-10-08 10:45:04

--
-- PostgreSQL database dump complete
--

\unrestrict pKKZaASOAVNp7cEHCKQWSLCti4hgjRc94EudQsvxtvROoLCYlNh4rdJZxOWQEkH

